### PR TITLE
Fix crash when video fails to load

### LINKED ISSUE #764: Crash when opening songs with MPG/FLV videos
### Actual behaviour

Ultrastar Deluxe crashes when opening songs that contain a video with MPG or FLV ending

### Expected behaviour

Song should be played with the video

### Details

**terminal output**
$ flatpak run --branch=stable --arch=x86_64 --command=ultrastardx eu.usdx.UltraStarDeluxe
Sorry, an error ocurred! Please report this error to the game-developers. Also check the Error.log file in the game folder.
Stacktrace:
Exception class: EAccessViolation
Message: Access violation
  $000000000050B3AB

**USDX error.log (last entries)**
INFO:   VideoStreamIndex : 0 [TVideoPlayback_ffmpeg.Open]
INFO:   Using h264 codec [TVideoPlayback_ffmpeg.Open]
INFO:   Framerate: 30fps [TVideoPlayback_ffmpeg.Open]
INFO:   Using decoder FFmpeg_Decoder for "/home/.ultrastardx/songs/Ultrastar 90s (Radio Pop)/All 4 One - I Swear [VIDEO]/All 4 One - I Swear.mp3" [TAudioPlaybackBase.OpenDecodeStream]
ERROR:  Failed to open file "/home/.ultrastardx/songs/Ultrastar 90s (Radio Pop)/All 4 One - I Swear [VIDEO]/All 4 One - I Swear [VD#0].mpg" (::-1094995529)
STATUS: Begin [OnShow]
ERROR:  Failed to open file "/home/.ultrastardx/songs/Ultrastar 90s (Radio Pop)/All 4 One - I Swear [VIDEO]/All 4 One - I Swear [VD#0].mpg" (::-1094995529)
STATUS: Closing DB file [Finalization]
INFO:   TDataBaseSystem.Free [TDataBaseSystem.Destroy]
STATUS: Finalize Media [Finalization]
STATUS: Uninitialize 3D [Finalization]
STATUS: Kill Fonts [UnloadFontTextures]
STATUS: Finalize SDL [Finalization]
STATUS: Finalize Log [Finalization]

**The video is being played outside USDX with no problems.**

- USDX version: 2023-09 as flatpak
- Operating System + version: Linux (siduction/Debian unstable)

### PR DESCRIPTION
**Pull request by s09bQ5**
Fixes #764.
Broken since 983dc2f003466269eb84475defae3815405b1099

### CODE REVIEW

File: src/screens/controllers/UScreenSingController.pas [hunk 1]
```diff
@@ -1088,9 +1088,9 @@ procedure TScreenSingController.LoadNextSong();
   begin
     fVideoClip := VideoPlayback.Open(VideoFile);
     fCurrentVideo := fVideoClip;
```
Comment (barbeque-squared) [inline src/screens/controllers/UScreenSingController.pas:1090]: would it be possible to also move this line to inside the `if`? the function initially sets `fCurrentVideo := nil` at the beginning, it would make things more intuitive.
technically the PR as-is would fix the problem it's trying to address, but the assigning _before_ the `if` is what probably threw me when I changed this. I'll leave it open for a day or so if you want to commit it yourself, otherwise I'll just do it before merging.

Comment (s09bQ5) [reply src/screens/controllers/UScreenSingController.pas]: done

**Review by basisbit — APPROVED** [review]
